### ISSUE TITLE
Lighthouse crossorigin warnings despite using this plugin

### ISSUE THREAD

**Issue by styxlab** [NoriSte/gatsby-plugin-preload-link-crossorigin#369]
Thanks a lot for providing this plugin!

I'm using Lighthouse 6.1.0 from the command line (also tested it with LH 6.0.0 and chrome devtools) and cannot figure out how to get rid of multiple warnings of the form:

```
A preload <link> was found for "http://localhost:9000/page-data/app-data.json" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
```

Note that I am using the `gatsby-plugin-preload-link-crossorigin` plugin. The plugin does add the `crossorigin` attribute to the `preload links`, but the warning remains. Looks like the gatsby-offline plugin kicks in, which I want to keep.

# Steps to reproduce

Clone the standard `gatby-starter-blog`, but with `gatsby-plugin-preload-link-crossorigin` and `gatsby-plugin-offline` added:

```
$ git clone https://github.com/styxlab/gatsby-starter-blog.git
$ cd gatsby-starter-blog
$ yarn; yarn build
$ gatsby serve
$ lighthouse http://localhost:9000 --only-categories=performance --view
```
![image](https://user-images.githubusercontent.com/19638263/85933193-a17b2080-b8d4-11ea-8344-65e18ff06307.png)

# Remove `preload-link-crossorigin` *and* `offline-plugin`
```
$ git checkout remove-preload-link-crossorigin
$ yarn clean; yarn build
$ gatsby serve
$ lighthouse http://localhost:9000 --only-categories=performance --view
```
![image](https://user-images.githubusercontent.com/19638263/85933347-5235ef80-b8d6-11ea-9fe0-ee40035f1e20.png)

This looks good, but I had to remove the `offline-plugin` which I need.

# Add the `preload-link-crossorigin` plugin again (offline plugin removed)
```
$ git checkout remove-offline
$ yarn clean; yarn build
$ gatsby serve
$ lighthouse http://localhost:9000 --only-categories=performance --view
```
![image](https://user-images.githubusercontent.com/19638263/85933396-dbe5bd00-b8d6-11ea-847c-13fde4c4046c.png)

Now the warning is appearing again, even without the offline plugin, so it looks like  `gatsby-plugin-preload-link-crossorigin` is causing the issue instead of solving it.

I hope you can give some insight as to why this plugin does not have the desired effects. Thanks for your time!

**Comment by NoriSte** [comment]
First of all, thanks for the detailed feedback, this is a perfect issue-reporting 😊 I link #351 where we discussed it and if you want to add minimatch and raising a PR you're more than welcome 😊

**Comment by styxlab** [comment]
Thanks for looking into this. Are you sure #351 is the same root cause?

**Comment by NoriSte** [comment]
I think so, you could try to change the code of the plugin checking if the problem disappears. In order to do so:

- open `node_modules/gatsby-plugin-preload-link-crossorigin/gatsby-ssr.js`
- replace
```js
if (component.type === "link" && component.props && component.props.rel === "preload") {
```
with
```js
if (component.type === "link" && component.props && component.props.rel === "preload" && !component.props.href.startsWith("/")) {
```
and check if Gatsby reports the same error.

Please let us know, thanks @styxlab 😊

**Comment by styxlab** [comment]
Thanks for your suggestion, but I won't have time to follow up on this. I think the issue should be solved upstream - however, your plugin could serve as a transient solution after being enhanced.

**Comment by NoriSte** [comment]
Don't you have the time to try the change I suggested? It's just a matter of a file change and a `npm run serve`/`build` 😊 anyway, thanks for the detailed report 😉

**Comment by lvtz** [comment]
@NoriSte 
> and check if Gatsby reports the same error.

I can confirm that is not resolved this issue. After applying your suggested patch seems to don't get an expected result.

I haven't noticed this issue on the localhost, faced it on production build, with the newest Google Chrome and Vercel.

![2020-08-7 o 14 25 52](https://user-images.githubusercontent.com/18595528/89645817-ee321e00-d8ba-11ea-90d1-de3cef0b7493.png)

**Comment by mbcod3** [comment]
I think the console warning is caused by crossorigin being empty and not set to anonymouse on a production build. This plugin is also not setting crossorigin to anyonymous because after using it the links still have crossorigin="". 

This plugin is not solving the issue.

**Comment by NoriSte** [comment]
As reported on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin)

> Setting the attribute name to an empty value, like crossorigin or crossorigin="", is the same as anonymous.

Could you check out if setting it to `anonymous` produce any relevant change, please? It shouldn't

**Comment by mbcod3** [comment]
You are right mdn does say that but the thing is after using the plugin I still get the same error. 

How do I remove preload to scripts that are not being used on window load?

**Comment by NoriSte** [comment]
I'm thinking about deprecating this module since it's more an annoyance than a help 😉

**Comment by NoriSte** [comment]
Done, I deprecated this package 😉
